apiVersion: v1
kind: Service
metadata:
  name: work-harness
  labels:
    app: work-harness
spec:
  selector:
    app: work-harness
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
